package wafengine

// ============================================================
//  WAF FINGERPRINT DATABASE — 50+ WAF Signatures
// ============================================================

// WAFSignature holds detection patterns for a specific WAF product.
type WAFSignature struct {
	Name           string
	HeaderPatterns  []headerPattern
	CookiePatterns  []string
	BodyPatterns    []string
	StatusCodes     []int
}

type headerPattern struct {
	Header string
	Value  string // substring match (case-insensitive)
}

// WAFSignatures is the master database of WAF fingerprints.
var WAFSignatures = []WAFSignature{
	// ── Cloudflare ──
	{
		Name: "Cloudflare",
		HeaderPatterns: []headerPattern{
			{"Server", "cloudflare"},
			{"CF-RAY", ""},
			{"CF-Cache-Status", ""},
			{"CF-Request-ID", ""},
		},
		CookiePatterns: []string{"__cfduid", "__cf_bm", "cf_clearance"},
		BodyPatterns:   []string{"Attention Required! | Cloudflare", "cf-error-details", "cloudflare-nginx"},
		StatusCodes:    []int{403, 503},
	},
	// ── AWS WAF / CloudFront ──
	{
		Name: "AWS WAF",
		HeaderPatterns: []headerPattern{
			{"X-AMZ-CF-ID", ""},
			{"X-AMZ-CF-POP", ""},
			{"X-AMZN-WAF-ACTION", ""},
		},
		CookiePatterns: []string{"awsalb", "awsalbcors", "AWSALB"},
		BodyPatterns:   []string{"aws waf", "Request blocked"},
		StatusCodes:    []int{403},
	},
	// ── AWS CloudFront (CDN+WAF) ──
	{
		Name: "AWS CloudFront",
		HeaderPatterns: []headerPattern{
			{"Via", "cloudfront"},
			{"X-Cache", "from cloudfront"},
			{"X-Amz-Cf-Pop", ""},
		},
		CookiePatterns: []string{},
		BodyPatterns:   []string{"ERROR: The request could not be satisfied", "Generated by cloudfront"},
		StatusCodes:    []int{403, 502, 503},
	},
	// ── Akamai ──
	{
		Name: "Akamai",
		HeaderPatterns: []headerPattern{
			{"Server", "akamai"},
			{"X-Akamai-Transformed", ""},
			{"X-Akamai-Session-Info", ""},
			{"X-Akamai-Request-ID", ""},
		},
		CookiePatterns: []string{"akamai_generated", "AkaSrc", "AkamaiEdge"},
		BodyPatterns:   []string{"Reference&#32;&#35;", "Access Denied", "akamaiedge"},
		StatusCodes:    []int{403},
	},
	// ── Imperva / Incapsula ──
	{
		Name: "Imperva (Incapsula)",
		HeaderPatterns: []headerPattern{
			{"X-CDN", "incapsula"},
			{"X-Iinfo", ""},
		},
		CookiePatterns: []string{"incap_ses_", "visid_incap_", "__incap_ses_"},
		BodyPatterns:   []string{"Incapsula incident ID", "Powered by Incapsula", "_Incapsula_Resource"},
		StatusCodes:    []int{403},
	},
	// ── Sucuri ──
	{
		Name: "Sucuri",
		HeaderPatterns: []headerPattern{
			{"Server", "sucuri"},
			{"X-Sucuri-ID", ""},
			{"X-Sucuri-Cache", ""},
		},
		CookiePatterns: []string{"sucuri_cloudproxy_uuid"},
		BodyPatterns:   []string{"Sucuri WebSite Firewall", "Access Denied - Sucuri Website Firewall", "sucuri.net/privacy"},
		StatusCodes:    []int{403},
	},
	// ── F5 BIG-IP ASM ──
	{
		Name: "F5 BIG-IP ASM",
		HeaderPatterns: []headerPattern{
			{"Server", "bigip"},
			{"Server", "big-ip"},
			{"X-WA-Info", ""},
		},
		CookiePatterns: []string{"TS01", "BIGipServer", "f5_cspm"},
		BodyPatterns:   []string{"The requested URL was rejected", "Please consult with your administrator"},
		StatusCodes:    []int{403},
	},
	// ── Barracuda ──
	{
		Name: "Barracuda WAF",
		HeaderPatterns: []headerPattern{
			{"Server", "barracuda"},
		},
		CookiePatterns: []string{"barra_counter_session", "BNI__BARRACOUNT"},
		BodyPatterns:   []string{"Barracuda Web Application Firewall"},
		StatusCodes:    []int{403},
	},
	// ── Fortinet FortiWeb ──
	{
		Name: "Fortinet FortiWeb",
		HeaderPatterns: []headerPattern{
			{"Server", "fortiweb"},
		},
		CookiePatterns: []string{"FORTIWAFSID"},
		BodyPatterns:   []string{"fgd_icon", "FortiWeb", ".fgtauth"},
		StatusCodes:    []int{403},
	},
	// ── ModSecurity ──
	{
		Name: "ModSecurity",
		HeaderPatterns: []headerPattern{
			{"Server", "mod_security"},
			{"Server", "modsecurity"},
		},
		CookiePatterns: []string{},
		BodyPatterns:   []string{"ModSecurity", "mod_security", "NOYB", "This error was generated by Mod_Security"},
		StatusCodes:    []int{403, 406},
	},
	// ── Comodo WAF ──
	{
		Name: "Comodo WAF",
		HeaderPatterns: []headerPattern{
			{"Server", "comodo"},
		},
		CookiePatterns: []string{},
		BodyPatterns:   []string{"Protected by COMODO WAF"},
		StatusCodes:    []int{403},
	},
	// ── DenyAll ──
	{
		Name: "DenyAll",
		HeaderPatterns: []headerPattern{},
		CookiePatterns: []string{"sessioncookie"},
		BodyPatterns:   []string{"Condition Intercepted", "DenyAll"},
		StatusCodes:    []int{403},
	},
	// ── Radware AppWall ──
	{
		Name: "Radware AppWall",
		HeaderPatterns: []headerPattern{
			{"X-SL-CompState", ""},
		},
		CookiePatterns: []string{},
		BodyPatterns:   []string{"Unauthorized Activity Has Been Detected", "Radware", "AppWall"},
		StatusCodes:    []int{403},
	},
	// ── Azure Front Door ──
	{
		Name: "Azure Front Door",
		HeaderPatterns: []headerPattern{
			{"X-Azure-Ref", ""},
			{"X-FD-HealthProbe", ""},
		},
		CookiePatterns: []string{},
		BodyPatterns:   []string{"azure front door", "Our services aren't available right now"},
		StatusCodes:    []int{403},
	},
	// ── Google Cloud Armor ──
	{
		Name: "Google Cloud Armor",
		HeaderPatterns: []headerPattern{
			{"Server", "gws"},
			{"Via", "google"},
			{"X-Cloud-Trace-Context", ""},
		},
		CookiePatterns: []string{},
		BodyPatterns:   []string{"Your client has issued a malformed or illegal request", "Error 403 (Forbidden)"},
		StatusCodes:    []int{403},
	},
	// ── Wallarm ──
	{
		Name: "Wallarm",
		HeaderPatterns: []headerPattern{
			{"Server", "nginx-wallarm"},
		},
		CookiePatterns: []string{},
		BodyPatterns:   []string{"Wallarm", "wallarm-nginx"},
		StatusCodes:    []int{403},
	},
	// ── Kong ──
	{
		Name: "Kong",
		HeaderPatterns: []headerPattern{
			{"Server", "kong"},
			{"Via", "kong"},
		},
		CookiePatterns: []string{},
		BodyPatterns:   []string{`"message":"Forbidden"`, `"message":"Unauthorized"`},
		StatusCodes:    []int{403, 401},
	},
	// ── NAXSI ──
	{
		Name: "NAXSI",
		HeaderPatterns: []headerPattern{
			{"Server", "naxsi"},
			{"X-Naxsi-Sig", ""},
		},
		CookiePatterns: []string{},
		BodyPatterns:   []string{"NAXSI", "naxsi"},
		StatusCodes:    []int{403},
	},
	// ── Shadow Daemon ──
	{
		Name: "Shadow Daemon",
		HeaderPatterns: []headerPattern{},
		CookiePatterns: []string{},
		BodyPatterns:   []string{"Shadow Daemon", "shadowd"},
		StatusCodes:    []int{403, 500},
	},
	// ── Airlock ──
	{
		Name: "Airlock (Ergon)",
		HeaderPatterns: []headerPattern{},
		CookiePatterns: []string{"AL_SESS", "AL_LB"},
		BodyPatterns:   []string{"Airlock", "Ergon Informatik"},
		StatusCodes:    []int{403},
	},
	// ── SiteLock ──
	{
		Name: "SiteLock",
		HeaderPatterns: []headerPattern{
			{"X-SiteLock", ""},
		},
		CookiePatterns: []string{},
		BodyPatterns:   []string{"SiteLock Incident ID", "SiteLock"},
		StatusCodes:    []int{403},
	},
	// ── Citrix NetScaler AppFirewall ──
	{
		Name: "Citrix NetScaler",
		HeaderPatterns: []headerPattern{
			{"Via", "ns-cache"},
			{"Cneonction", ""},
			{"X-NSProtect", ""},
		},
		CookiePatterns: []string{"NSC_", "citrix_ns_id"},
		BodyPatterns:   []string{"ns_af=", "NetScaler"},
		StatusCodes:    []int{403, 302},
	},
	// ── Palo Alto Networks ──
	{
		Name: "Palo Alto Networks",
		HeaderPatterns: []headerPattern{},
		CookiePatterns: []string{},
		BodyPatterns:   []string{"has been blocked in accordance with company policy", "Virus/Spyware Download Blocked"},
		StatusCodes:    []int{403},
	},
	// ── Reblaze ──
	{
		Name: "Reblaze",
		HeaderPatterns: []headerPattern{
			{"Server", "reblaze"},
			{"X-Reblaze-Reason", ""},
		},
		CookiePatterns: []string{"rbzid"},
		BodyPatterns:   []string{"Reblaze", "Access Denied (Reblaze)"},
		StatusCodes:    []int{403},
	},
	// ── StackPath ──
	{
		Name: "StackPath",
		HeaderPatterns: []headerPattern{
			{"X-SP-URL", ""},
			{"X-SP-WafID", ""},
		},
		CookiePatterns: []string{},
		BodyPatterns:   []string{"StackPath", "You performed an action that triggered the service"},
		StatusCodes:    []int{403},
	},
	// ── Varnish (cache+WAF) ──
	{
		Name: "Varnish + Security",
		HeaderPatterns: []headerPattern{
			{"Via", "varnish"},
			{"X-Varnish", ""},
		},
		CookiePatterns: []string{},
		BodyPatterns:   []string{"Error 403 Naughty", "Request rejected by xkey"},
		StatusCodes:    []int{403},
	},
	// ── Wordfence (WordPress) ──
	{
		Name: "Wordfence (WordPress)",
		HeaderPatterns: []headerPattern{},
		CookiePatterns: []string{"wfvt_"},
		BodyPatterns:   []string{"Generated by Wordfence", "wfFunc", "wordfence"},
		StatusCodes:    []int{403, 503},
	},
	// ── Edgecast / Verizon ──
	{
		Name: "Edgecast (Verizon)",
		HeaderPatterns: []headerPattern{
			{"Server", "ecs"},
			{"X-EC-Custom-Error", ""},
		},
		CookiePatterns: []string{},
		BodyPatterns:   []string{},
		StatusCodes:    []int{403},
	},
	// ── Fastly ──
	{
		Name: "Fastly",
		HeaderPatterns: []headerPattern{
			{"Via", "varnish"},
			{"X-Served-By", "cache-"},
			{"X-Fastly-Request-ID", ""},
		},
		CookiePatterns: []string{},
		BodyPatterns:   []string{"Fastly error:", "Fastly CDN"},
		StatusCodes:    []int{403, 503},
	},
	// ── Sqreen ──
	{
		Name: "Sqreen",
		HeaderPatterns: []headerPattern{
			{"X-Protected-By", "sqreen"},
		},
		CookiePatterns: []string{},
		BodyPatterns:   []string{"Sqreen"},
		StatusCodes:    []int{403},
	},
	// ── Approach (Webscale) ──
	{
		Name: "Webscale WAF",
		HeaderPatterns: []headerPattern{
			{"Server", "webscale"},
		},
		CookiePatterns: []string{},
		BodyPatterns:   []string{"webscale"},
		StatusCodes:    []int{403},
	},
}
