package models

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"strings"
	"sync"
	"time"
)

// SharedData is a global concurrent map for sharing data between plugins
var SharedData sync.Map

// SharedData key prefixes — always append the target hostname.
const (
	KeyPrefixSiteMap    = "sitemap_"    // *sitemapper.SiteMap
	KeyPrefixEndpoints  = "endpoints_"  // []models.Endpoint
	KeyPrefixForbidden  = "forbidden_"  // []string (403/401 paths + robots disallows)
	KeyPrefixJSFiles    = "jsfiles_"    // []string (JS file URLs)
	KeyPrefixTechProfile = "techprofile_" // *models.TechProfile
)

type ScanTarget struct {
	IP   string
	Port int
}

type Endpoint struct {
	URL    string
	Method string
	Params []string
}

type Vulnerability struct {
	Target      ScanTarget
	Name        string
	Severity    string
	CVSS        float64
	Description string
	Solution    string
	Reference   string
	Status      string
}

type ScannerPlugin interface {
	Name() string
	Run(target ScanTarget) *Vulnerability
}

// Function pointer to avoid circular dependencies when plugins need the HTTP client
var GetClient func() *http.Client


type TechNode struct {
    Product string
    Version string
}

type TechProfile struct {
    Techs []TechNode
    WAF   string
    CMS   string
}

type LocalCVE struct {
    ID            string  `json:"id"`
    Product       string  `json:"product"`
    Version       string  `json:"version"`
    CVSS          float64 `json:"cvss"`
    VendorProject string  `json:"vendorProject"`
    Description   string  `json:"description"`
    Severity      string  `json:"severity"`
}

var DeepScanTarget func(targetURL string) *TechProfile
var SearchLocalCVEs func(product, version string) []LocalCVE
var GetCVEByID func(id string) *LocalCVE
var SearchExploitDB func(query string) []string

// ==========================================
// DORM VECTORS — cross-package scan-engine bridge
// ==========================================
//
// The vectors package (vectors/) needs to trigger a real scan run, but the
// actual engine (Engine/NewEngine/AddPlugin/SetActiveClient) lives in the
// root package main, which no other package may import. ScanRunConfig,
// ScanOutcome and RunScan below are the shared vocabulary that lets vectors
// ask main to run a scan without ever importing it — the same function-
// pointer idiom already used for GetClient/DeepScanTarget/SearchLocalCVEs
// above and for sitemapper.OnSiteMapReady.

// ScanRunConfig describes one scan pass — used by both the classic ad-hoc
// /scan endpoint and by DORM Vectors.
type ScanRunConfig struct {
	Targets      []string
	PluginFilter string
	AuthHeader   string
	ProxyEnabled bool
	ProxyURL     string
	WAFDelayMs   int
	WAFJitterMs  int
	CVERadar     bool
}

// ScanOutcome is the result of one completed (or stopped/failed) scan pass.
type ScanOutcome struct {
	Status          string // "Completed" | "Failed" | "Stopped"
	StartTime       time.Time
	EndTime         time.Time
	Vulnerabilities []*Vulnerability
	TotalVulns      int
	SeverityStats   map[string]int
}

// RunScan is wired by main at startup to the real scan engine. scanID is
// generated by the caller up front (the sitemapper pre-scan needs it before
// the run even starts); onStart reports back the sanitized/joined target
// title as soon as it's known, so the caller can persist an initial
// "Running" record before the scan actually begins.
var RunScan func(ctx context.Context, scanID string, cfg ScanRunConfig, emit func(payload string), onStart func(target string)) ScanOutcome

// ==========================================
// SHARED HELPERS FOR ENGINE SUB-PACKAGES
// ==========================================

// IsWebPort returns true if the port is a common web port.
func IsWebPort(port int) bool {
	return port == 80 || port == 443 || port == 8080 || port == 8443 || port == 3000 || port == 5000 || port == 9090
}

// GetURL constructs a full URL from a ScanTarget and optional path.
func GetURL(target ScanTarget, path string) string {
	proto := "http"
	if target.Port == 443 || target.Port == 8443 {
		proto = "https"
	}
	if !strings.HasPrefix(path, "/") && path != "" {
		path = "/" + path
	}
	return fmt.Sprintf("%s://%s:%d%s", proto, target.IP, target.Port, path)
}

// ReadBody reads the response body up to maxBytes and closes it.
func ReadBody(resp *http.Response, maxBytes int64) string {
	if resp == nil {
		return ""
	}
	defer func() { _ = resp.Body.Close() }()
	b, _ := io.ReadAll(io.LimitReader(resp.Body, maxBytes))
	return string(b)
}

// GetSharedString reads a string value from SharedData.
func GetSharedString(key string) string {
	v, ok := SharedData.Load(key)
	if !ok {
		return ""
	}
	s, ok := v.(string)
	if !ok {
		return ""
	}
	return s
}
